// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package rating_test

import (
	"github.com/gin-gonic/gin"
	"github.com/klins/devpool/go-day6/wongnok/internal/model"
	"github.com/klins/devpool/go-day6/wongnok/internal/model/dto"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIHandler creates a new instance of MockIHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIHandler {
	mock := &MockIHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIHandler is an autogenerated mock type for the IHandler type
type MockIHandler struct {
	mock.Mock
}

type MockIHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIHandler) EXPECT() *MockIHandler_Expecter {
	return &MockIHandler_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockIHandler
func (_mock *MockIHandler) Create(ctx *gin.Context) {
	_mock.Called(ctx)
	return
}

// MockIHandler_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIHandler_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx *gin.Context
func (_e *MockIHandler_Expecter) Create(ctx interface{}) *MockIHandler_Create_Call {
	return &MockIHandler_Create_Call{Call: _e.mock.On("Create", ctx)}
}

func (_c *MockIHandler_Create_Call) Run(run func(ctx *gin.Context)) *MockIHandler_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIHandler_Create_Call) Return() *MockIHandler_Create_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIHandler_Create_Call) RunAndReturn(run func(ctx *gin.Context)) *MockIHandler_Create_Call {
	_c.Run(run)
	return _c
}

// GetByID provides a mock function for the type MockIHandler
func (_mock *MockIHandler) GetByID(ctx *gin.Context) {
	_mock.Called(ctx)
	return
}

// MockIHandler_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockIHandler_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx *gin.Context
func (_e *MockIHandler_Expecter) GetByID(ctx interface{}) *MockIHandler_GetByID_Call {
	return &MockIHandler_GetByID_Call{Call: _e.mock.On("GetByID", ctx)}
}

func (_c *MockIHandler_GetByID_Call) Run(run func(ctx *gin.Context)) *MockIHandler_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIHandler_GetByID_Call) Return() *MockIHandler_GetByID_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIHandler_GetByID_Call) RunAndReturn(run func(ctx *gin.Context)) *MockIHandler_GetByID_Call {
	_c.Run(run)
	return _c
}

// NewMockIRepository creates a new instance of MockIRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIRepository {
	mock := &MockIRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIRepository is an autogenerated mock type for the IRepository type
type MockIRepository struct {
	mock.Mock
}

type MockIRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIRepository) EXPECT() *MockIRepository_Expecter {
	return &MockIRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockIRepository
func (_mock *MockIRepository) Create(rating *model.Rating) error {
	ret := _mock.Called(rating)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*model.Rating) error); ok {
		r0 = returnFunc(rating)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - rating *model.Rating
func (_e *MockIRepository_Expecter) Create(rating interface{}) *MockIRepository_Create_Call {
	return &MockIRepository_Create_Call{Call: _e.mock.On("Create", rating)}
}

func (_c *MockIRepository_Create_Call) Run(run func(rating *model.Rating)) *MockIRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.Rating
		if args[0] != nil {
			arg0 = args[0].(*model.Rating)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIRepository_Create_Call) Return(err error) *MockIRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIRepository_Create_Call) RunAndReturn(run func(rating *model.Rating) error) *MockIRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockIRepository
func (_mock *MockIRepository) GetByID(id int) (model.Ratings, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 model.Ratings
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) (model.Ratings, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(int) model.Ratings); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(model.Ratings)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockIRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id int
func (_e *MockIRepository_Expecter) GetByID(id interface{}) *MockIRepository_GetByID_Call {
	return &MockIRepository_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *MockIRepository_GetByID_Call) Run(run func(id int)) *MockIRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIRepository_GetByID_Call) Return(ratings model.Ratings, err error) *MockIRepository_GetByID_Call {
	_c.Call.Return(ratings, err)
	return _c
}

func (_c *MockIRepository_GetByID_Call) RunAndReturn(run func(id int) (model.Ratings, error)) *MockIRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIService creates a new instance of MockIService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIService {
	mock := &MockIService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIService is an autogenerated mock type for the IService type
type MockIService struct {
	mock.Mock
}

type MockIService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIService) EXPECT() *MockIService_Expecter {
	return &MockIService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockIService
func (_mock *MockIService) Create(request dto.RatingRequest, recipeID int) (model.Rating, error) {
	ret := _mock.Called(request, recipeID)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 model.Rating
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(dto.RatingRequest, int) (model.Rating, error)); ok {
		return returnFunc(request, recipeID)
	}
	if returnFunc, ok := ret.Get(0).(func(dto.RatingRequest, int) model.Rating); ok {
		r0 = returnFunc(request, recipeID)
	} else {
		r0 = ret.Get(0).(model.Rating)
	}
	if returnFunc, ok := ret.Get(1).(func(dto.RatingRequest, int) error); ok {
		r1 = returnFunc(request, recipeID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - request dto.RatingRequest
//   - recipeID int
func (_e *MockIService_Expecter) Create(request interface{}, recipeID interface{}) *MockIService_Create_Call {
	return &MockIService_Create_Call{Call: _e.mock.On("Create", request, recipeID)}
}

func (_c *MockIService_Create_Call) Run(run func(request dto.RatingRequest, recipeID int)) *MockIService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 dto.RatingRequest
		if args[0] != nil {
			arg0 = args[0].(dto.RatingRequest)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIService_Create_Call) Return(rating model.Rating, err error) *MockIService_Create_Call {
	_c.Call.Return(rating, err)
	return _c
}

func (_c *MockIService_Create_Call) RunAndReturn(run func(request dto.RatingRequest, recipeID int) (model.Rating, error)) *MockIService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockIService
func (_mock *MockIService) GetByID(id int) (model.Ratings, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 model.Ratings
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) (model.Ratings, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(int) model.Ratings); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(model.Ratings)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockIService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id int
func (_e *MockIService_Expecter) GetByID(id interface{}) *MockIService_GetByID_Call {
	return &MockIService_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *MockIService_GetByID_Call) Run(run func(id int)) *MockIService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIService_GetByID_Call) Return(ratings model.Ratings, err error) *MockIService_GetByID_Call {
	_c.Call.Return(ratings, err)
	return _c
}

func (_c *MockIService_GetByID_Call) RunAndReturn(run func(id int) (model.Ratings, error)) *MockIService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}
